### ISSUE TITLE
GdsImport does not support texttype

### ISSUE THREAD

**Issue by tom-varga** [hohlraum/gdsCAD#20]
Is it correct that GdsImport does not currently support texttype?
I see in the code some commented out lines that refer to texttype.
The texttype is used in all chip layouts.
Would supporting texttype be something relatively easy to add?
Thanks,
-Tom

**Comment by hohlraum** [comment]
Hi Tom,

This was caused by a combination of bad docs (in gdsCAD texttype=datatype) and a bug (that used texttype as an argument). Commit c2b1e6a1d7 should fix both. Thanks for bringing this up.

GdsImport does support Text objects. However the texttype record is converted in gdsCAD to the ```datatype``` attribute. It is similarly converted on save to texttype which will be understood by other programs. There should not be any conflicts in equating texttype with datatype since no drawing element possesses both.

**Comment by tom-varga** [comment]
Andrew, thanks for so quickly looking into this for me!
I'm a github newbie and would really appreciate a bit of help with trying to pull your update.
I think this is the way to do it, but it doesn't work for me.
> mkdir gdsCAD
> cd !$
> git clone https://github.com/hohlraum/gdsCAD.git
> git pull origin master

However, the 'git clone' doesn't do anything for me.
Would you be so kind as to how to get your latest c2b1e6a commit?
Thanks,
-Tom

**Comment by tom-varga** [comment]
Andrew, please ignore my prior query.
Apparently, my version of git was quietly dumping core.
Switching to an older version fixed my problem.
Thanks,
-Tom
