### ISSUE TITLE
When I am installing this, it is showing error.

### ISSUE THREAD

**Issue by vishalvashistha87** [hohlraum/gdsCAD#39]
Here is the log of my system. please someone help. I am new in Linux. 

hegder@hegder-Inspiron-3543:~/Downloads/gdsCAD-master$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    version = get_version(),
  File "/home/hegder/Downloads/gdsCAD-master/git_version.py", line 100, in get_version
    raise ValueError("Cannot find the version number!")
ValueError: Cannot find the version number!
hegder@hegder-Inspiron-3543:~/Downloads/gdsCAD-master$

**Comment by muab** [comment]
I had this small problem too, because the repository is not updated in the python reps (last one there is version '0.4.5'). but the master here is '0.5.0'.
if this current master version is the one you are trying to install all you have to do is substitute in the corresponding setup.py the line:
version = get_version(),
for the line:
version = '0.5.0',
and then execute again: sudo python setup.py install
